import {
  FONT_SIZES,
  FONT_FAMILLY,
  FONT_WEIGHT,
  COLORS,
} from "../constants/contansts";

const THEME_SCHEME = {
  COLORS: COLORS,
  FONT_FAMILY: FONT_FAMILLY,
  FONT_SIZES: FONT_SIZES,
  FONT_WEIGHT: FONT_WEIGHT,
};

export default THEME_SCHEME;
